### PR TITLE
Use explicit relative imports where reasonable

### PR DESCRIPTION
**Pull request by blag**

### CODE REVIEW

**Comment by mkurek** [comment]
@blag could you provide some reason for doing this (relative imports)?

**Comment by blag** [comment]
@mkurek

There are actually two types of changes I made in this PR.

The first change was converting absolute imports to explicit relative imports: `from powerdns.models import ...` to `from .models import ...` (for modules in the `powerdns` package). I find relative imports easier to look at, and using relative imports allow the package to be renamed without having to refactor any inter-module imports. Explicit relative imports are supported in both [Python 2.5+ and 3](http://stackoverflow.com/a/33243918/6461688). Note that almost all of the problems with relative imports are complaints about _implicit_ relative imports, and all of these changes are _explicit_ relative imports.

---

Edit: This second change was split out into #167, commit 015abbc.

The second change I made was to remove the imports to submodules of `powerdns.models`, because I think that inappropriately couples code to implementation details. Consider what would happen if the `CryptoKey` model was moved from `powerdns/models/powerdns.py` to `powerdns/models/tsigkeys.py` - every single `from powerdns.models.powerdns import CryptoKey` would need to be refactored to `from powerdns.models.tsigkeys import CryptoKey`.

I changed the `powerdns/models/__init__.py` to (explicitly, relative) import all of the modules in that directory, and then imported all of the models from `powerdns.models`. That way, if a model moves between submodules, as long as it's imported in `__init__.py` no more refactoring needs to be done.

Here's an illustration:

`powerdns/models/__init__.py`:

``` python
...
from .powerdns import *  # this works too: from powerdns.models.powerdns import *
...
from .tsigkeys import *  # this works too: from powerdns.models.tsigkeys import *
```

``` python
from powerdns.models.powerdns import CryptoKey  # <-- works
from powerdns.models import CryptoKey  # <-- works
```

but once `CryptoKey` is moved from `powerdns/models/powerdns.py` to `powerdns/models/tsigkeys.py`:

``` python
from powerdns.models.powerdns import CryptoKey  # <-- breaks!
from powerdns.models import CryptoKey  # <-- still works
```

I hope I explained that well enough.

~~If you don't like the explicit relative imports I can take them out, but I think the second change - importing from `powerdns.models` instead of `powerdns.models.<submodule>` is still valuable.~~

**Comment by blag** [comment]
I'll rebase this against master once the tests pass.

**Comment by blag** [comment]
I split out change 2 into its own PR #167.

I'll rebase this on top of that to make it easier to review and accept/reject.

**Comment by mkurek** [comment]
@blag could you rebase it to current develop?

**Comment by blag** [comment]
@mkurek Done. 👍

**Review by szok — APPROVED** [review]
Please rebase/merge to develop

**Comment by blag** [comment]
I'm rebasing this off of #171 so you should be able to merge #196, then #171, then #166, in that order.

**Comment by blag** [comment]
Done rebasing - should be able to cleanly merge after #171 now.

**Review by mkurek — APPROVED** [review]

**Pull request merged**
