### PR TITLE
Remove backslashes from content when TXT

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mkurek** [comment]
Could you describe (in some comment in source code or docstring) why is this necessary? 

Btw, could we add the same cleaning for all records with striping whitespace characters from the beginning and the end of name and content?

**Comment by ghost** [comment]
@mkurek, will check it now?

**Comment by mkurek** [comment]
:ok:

**Comment by szok** [comment]
:ok:

**Pull request merged**
