### PR TITLE
[to discuss] Remove domain check during update and deletion.

### PR DESCRIPTION
**Pull request by ghost**
Record should be auto accepted when record is owned by user even when the
record is in not permitted domain.

### CODE REVIEW

**Comment by szok** [comment]
:ok:

**Comment by krzysztofzygmunt** [comment]
:ok:

**Comment by mkurek** [comment]
Is this still applicable considering #151 changes?

**Comment by ghost** [comment]
#151 will work a bit different and both solutions are conflicting.

**Comment by ghost** [comment]
We don't need anymore this concept since #151

**Pull request closed without merging**
