### PR TITLE
Replace dj.choices with django-model-utils

### PR DESCRIPTION
**Pull request by blag**
This is a backwards compatible change because django-model-utils supports the same syntactical sugar as dj.choices, and dj.choices implemented the choices as a `models.PositiveSmallIntegerField`.

Since dj.choices hasn't been updated in 1.5 years and doesn't support modern Django versions, I wanted to migrate away from it to a more up-to-date package.

This PR is backwards compatible even down to database migrations.

### CODE REVIEW

**Comment by mkurek** [comment]
> Since dj.choices hasn't been updated in 1.5 years

screen shot 2016-10-19 at 08 01 39

:weary::weary::weary::weary::weary:

To be honest I'd stay with dj.choices - it doesn't "officially" support Django > 1.7, but (as we can see) it's working with Django 1.8 (and probably with newer too). Besides that is has a couple of nice features like grouping choices, fetching choice by name or id (`name_from_id`, `raw_from_id` etc). 

I'd try to add tests for Django>1.7 to dj.choices - will you be satisfied then? :)

**Comment by blag** [comment]
You're looking at the wrong date - that's just the date the choices.py file was last updated.

This is the date you need to look at:

6e307bae-95d2-11e6-9026-80452ff6c56b

September 19th - that's a little bit later than April 2015:

screencapture-github-ambv-dj-choices-1476861514332

> To be honest I'd stay with dj.choices - it doesn't "officially" support Django > 1.7, but (as we can see) it's working with Django 1.8 (and probably with newer too).

As far as I can tell, dj.choices is abandoned. And while it may run under Django 1.8 with deprecation warnings about [SubfieldBase](https://github.com/ambv/dj.choices/blob/3f7df6d85c79474f67202284ad68ecfcfbc3a020/src/dj/choices/fields.py#L42) (which has been [deprecated since Django 1.8](https://docs.djangoproject.com/en/1.8/releases/1.8/#subfieldbase)), it flat out doesn't run on Django 1.10 (SubfieldBase was [removed in Django 1.10](https://docs.djangoproject.com/en/1.10/releases/1.10/#features-removed-in-1-10)).

On the other hand, django-model-utils tests with [Django 1.10 and Django master](https://github.com/carljm/django-model-utils/blob/master/tox.ini#L7).

> Besides that is has a couple of nice features like grouping choices

So does DMU. From the [docs](https://django-model-utils.readthedocs.io/en/latest/utilities.html#choices):

``` python
STATUS = Choices(
    ('Visible', [
        'new',
        'archived']),
    ('Invisible', [
        'draft',
        'deleted']),
)
```

which roughly renders as:
- Visible
  - new
  - archived
- Invisible
  - draft
  - deleted

> fetching choice by name or id (name_from_id, raw_from_id etc)

I may not completely understand this, but I think all of that is available in DMU:

``` python
GENERIC_CHOICES = Choices(
    (0, 'draft', _('Draft')),
    (1, 'published', _('Published')),
)

GENERIC_CHOICES[0]  # 'Draft'
GENERIC_CHOICES[1]  # 'Published'

GENERIC_CHOICES['draft']  # 'Draft'
GENERIC_CHOICES['published']  # 'Published'
```

**Comment by blag** [comment]
@mkurek If you can get dj.choices updated to support Django 1.10 I would totally be fine with continuing using it in django-powerdns-dnssec.

**Comment by mkurek** [comment]
@blag I've created PR to dj.choices for Django 1.10 support: https://github.com/ambv/dj.choices/pull/18

**Comment by blag** [comment]
Wow, that was merged quickly! I'll close this PR, thanks for handling that!

Now can you get @ambv to merge [my PR on html5lib-python](https://github.com/html5lib/html5lib-python/pull/303) (he's a maintainer for html5lib-python and the bleach project is waiting on that merge)? 😉

**Pull request closed without merging**
