### PR TITLE
Move dnsaas/admin.py to powerdns/admin.py

### PR DESCRIPTION
**Pull request by blag**
Nothing in `dnsaas/admin.py` even references dnsaas, so move it into the powerdns app.

### CODE REVIEW

**Review by mkurek — APPROVED** [review]

**Comment by ghost** [comment]
This could be merged when we clean sec/seo acceptance table.

**Comment by blag** [comment]
Added backwards compatibility shim.

**Comment by ghost** [comment]
@blag could we talk live or at least on gitter/slack/etc. to introduce each other and maybe settle common vision? :)

**Review by ghost — APPROVED** [review]

**Comment by blag** [comment]
Sure, I'm on Gitter.

**Comment by blag** [comment]
I think I messed up the rebase, hang on.

**Comment by blag** [comment]
There we go. Now each commit should be reviewable at a glance. One moves the file, the other adds a backwards compatibility shim.

**Pull request merged**
