### PR TITLE
Remove deprecated API v1

### PR DESCRIPTION
**Pull request by mzdeb**

### CODE REVIEW

**Comment by ghost** [comment]
Could you check that urls still works:
* /api/
* /api-docs/

?

**Comment by mzdeb** [comment]
- /api/ - 404
- /api-docs/ - 200 (works)

I'm not sure what to do with /api/ uri, it should not return new api as it might confuse, on the other hand 404 is also bad. Maybe static page with comment that API v1 is not available any more?

**Comment by ghost** [comment]
Let's stick with info static page.

**Comment by mzdeb** [comment]
sth like this

```python
from django.http import HttpResponse

def myview(request):
    return HttpResponse("API v1 was removed")
```

or full html page? :)

**Comment by ghost** [comment]
LGTM

**Review by mkurek — APPROVED** [review]

**Comment by ghost** [comment]
After rethink the case I think link inclusion to `api/v2` (and/or to `api-docs`) would be even better.
Will you add it? :)

**Comment by mzdeb** [comment]
I've added this. Could you check it?

**Review by andrzej-jankowski — APPROVED** [review]

**Pull request merged**
