### PR TITLE
Fix inability to create delegation records

### PR DESCRIPTION
**Pull request by iavael**
Uniq constraint in database schema prevents from creating delegation NS-records for subdomain, if they have same dns servers.

For example:
```
(delegation in zone example.com)
test.example.com. IN NS ns1.example.com
test.example.com. IN NS ns2.example.com

(zone test.example.com)
test.example.com. IN NS ns1.example.com
test.example.com. IN NS ns2.example.com
```

### CODE REVIEW

**Review by mkurek — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
@iavael will you fix build and regenerate migration?
Migration with number `0034` already exists, https://github.com/allegro/django-powerdns-dnssec/pull/187/files

**Review by quamilek — CHANGES_REQUESTED** [review]
@iavael fix broken tests.

**Comment by mkurek** [comment]
@iavael could you rebase to current develop?

**Comment by vi4m** [comment]
@mkurek maybe we can fix it by ourself - github allows now working on foreign branches.

**Comment by mzdeb** [comment]
This project is deprecated.

**Pull request closed without merging**
